#define TRUE 1
#define FALSE 2

#define MAX_ALARMS 10
#define ALARM_PACKET_LENGTH 3

#define ALARM_PACKET_HOUR_FIRST_DIGIT 0
#define ALARM_PACKET_HOUR_SECOND_DIGIT 1
#define ALARM_PACKET_MINUTE_FIRST_DIGIT 2
#define ALARM_PACKET_MINUTE_SECOND_DIGIT 3

#define __DEBUG__